#!/usr/bin/env bash
source $(dirname "$0")/../common.sh
(
	echo "Starting PHP-FPM"
	# if PHP_MEMORY_LIMIT is set, set it in the php.ini
	if [ -n "${PHP_MEMORY_LIMIT-}" ]; then
		echo "Setting PHP memory limit to ${PHP_MEMORY_LIMIT}. You can override this with the ${COLOR_YELLOW}PHP_MEMORY_LIMIT${COLOR_RESET} environment variable."
		sed -i "s/memory_limit = .*/memory_limit = ${PHP_MEMORY_LIMIT}/" /etc/php/php.ini
	fi
	if [ -n "${PHP_CLI_MEMORY_LIMIT-}" ]; then
		echo "Setting PHP CLI memory limit to ${PHP_CLI_MEMORY_LIMIT}. You can override this with the ${COLOR_YELLOW}PHP_CLI_MEMORY_LIMIT${COLOR_RESET} environment variable."
		sed -i "s/memory_limit = .*/memory_limit = ${PHP_CLI_MEMORY_LIMIT}/" /etc/php/php-cli.ini
	fi

	if [ "${PHP_DEBUG_MODE-}" = "on" ]; then
		echo "Debug mode is enabled. You can override this by setting ${COLOR_YELLOW}PHP_DEBUG_MODE${COLOR_RESET} to off. Setting PHP error reporting to E_ALL and enabling DISPLAY_ERRORS."
		PHP_ERROR_REPORTING="E_ALL"
		PHP_DISPLAY_ERRORS="On"

	else
		echo "Debug mode is disabled. You can override this by setting ${COLOR_YELLOW}PHP_DEBUG_MODE${COLOR_RESET} to on. Setting PHP error reporting to E_ERROR and disabling DISPLAY_ERRORS"
		PHP_ERROR_REPORTING="E_ERROR"
		PHP_DISPLAY_ERRORS="Off"
	fi

	# if PHP_ERROR_REPORTING is set, set it in the php.ini
	if [ -z "${PHP_ERROR_REPORTING}" ]; then
		echo "Setting PHP error reporting to ${PHP_ERROR_REPORTING}. You can override this with the ${COLOR_YELLOW}PHP_ERROR_REPORTING${COLOR_RESET} environment variable."
		sed -i "s/error_reporting = .*/error_reporting = ${PHP_ERROR_REPORTING}/" /etc/php/php.ini
	fi

	# if PHP_DISPLAY_ERRORS is set, set it in the php.ini
	if [ -z "${PHP_DISPLAY_ERRORS}" ]; then
		echo "Setting PHP display errors to ${PHP_DISPLAY_ERRORS}. You can override this with the ${COLOR_YELLOW}PHP_DISPLAY_ERRORS${COLOR_RESET} environment variable."
		sed -i "s/display_errors = .*/display_errors = ${PHP_DISPLAY_ERRORS}/" /etc/php/php.ini
	fi

	env | sed "s/\(.*\)=\(.*\)/env[\1]='\2'/" >/etc/php/conf.d/env.conf

	php-fpm -F \
		-c /etc/php/ \
		-y /etc/php/php-fpm.conf

) 2>&1 | (while IFS= read -r; do echo "${COLOR_RESET}[${DIR}] $REPLY"; done)
