#!/usr/bin/env bash
set -e
cd "$(dirname "$0")"
TARGET=${1:-""}
source $(dirname "$0")/.common.sh
function finish(){
    builder_destroy || true
    ring_bell
}

trap finish EXIT

# shellcheck disable=SC2086
builder_init

echo "Pulling base images ... "
docker_pull_base_images "Alpine.Dockerfile"

SECONDS=0;
docker \
  buildx \
  --builder $MULTIARCH_BUILDER_NAME \
    bake \
    --provenance=false \
    --push \
      $TARGET
echo "Base Image Build Complete in ${COLOR_GREEN}${SECONDS}${COLOR_RESET} seconds!"
echo "Build of base image target ${COLOR_YELLOW}'$TARGET'${COLOR_RESET} completed."
