services:
  php-84-healthchecks:
    build: &build-php
      context: .
      dockerfile: PHP.Dockerfile
      target: php-84-base
    configs: &configs-php
      - source: php_info
        target: /app/public/index.php
    ports:
      - "3084:80"
  php-81-healthchecks:
    build:
      <<: *build-php
      target: php-81-base
    configs: *configs-php
    ports:
      - "3081:80"
  php-74-healthchecks:
    build:
      <<: *build-php
      target: php-74-base
    configs: *configs-php
    ports:
      - "3074:80"
  php-84-node-healthchecks:
    build:
      <<: *build-php
      target: php-84-node-base
    configs: *configs-php
    ports:
      - "3184:80"
  php-81-node-healthchecks:
    build:
      <<: *build-php
      target: php-81-node-base
    configs: *configs-php
    ports:
      - "3181:80"
  magento-php-84-healthchecks:
    build: &build-magento
      dockerfile: Magento.Dockerfile
      target: magento-84-node-base
    configs: &configs-magento
      - source: php_info
        target: /app/pub/index.php
    ports:
      - "4084:80"
  magento-php-81-healthchecks:
    build:
      <<: *build-magento
      target: magento-81-node-base
    configs: *configs-magento
    ports:
      - "4081:80"
    environment:
      PHP_ENABLE_XDEBUG: "off"
      PHP_FPM_PM_MAX_CHILDREN: 4
      PHP_FPM_PM_START_SERVERS: 1
      PHP_FPM_PM_MIN_SPARE_SERVERS: 1
      PHP_FPM_PM_MAX_SPARE_SERVERS: 1
    develop:
      watch:
        - action: sync+restart
          path: fs/php-nginx/etc/services.d/php/run
          target: /etc/services.d/php/run
        - action: sync+exec
          path: fs/php-nginx/etc/services.d/nginx/run
          target: /etc/services.d/nginx/run

configs:
  php_info:
    content: |
      <?php
      phpinfo();
