include:
  - test-healthchecks.yml
  - test-versions-assertions.yml

services:
  test:
    image: alpine:3.22
    command: ["sleep", "infinity"]
    depends_on:
      # Validation scripts should just exit 0 if the container is happy
      base-22-assertions:
        condition: service_completed_successfully
      base-21-assertions:
        condition: service_completed_successfully
      base-18-assertions:
        condition: service_completed_successfully
      base-15-assertions:
        condition: service_completed_successfully

      # PHP related
      php-84-assertions:
        condition: service_completed_successfully
      php-81-assertions:
        condition: service_completed_successfully
      php-74-assertions:
        condition: service_completed_successfully
      php-84-node-assertions:
        condition: service_completed_successfully
      php-81-node-assertions:
        condition: service_completed_successfully
      magento-php-84-assertions:
        condition: service_completed_successfully
      magento-php-81-assertions:
        condition: service_completed_successfully

      # Java related
      java-21-assertions:
        condition: service_completed_successfully
      java-17-assertions:
        condition: service_completed_successfully
      java-11-assertions:
        condition: service_completed_successfully
      java-8-assertions:
        condition: service_completed_successfully
      java-21-war-machine-assertions:
        condition: service_completed_successfully
      java-17-war-machine-assertions:
        condition: service_completed_successfully
      java-11-war-machine-assertions:
        condition: service_completed_successfully
      java-21-tomcat-assertions:
        condition: service_completed_successfully
      java-17-tomcat-assertions:
        condition: service_completed_successfully
      java-11-tomcat-assertions:
        condition: service_completed_successfully
      java-8-tomcat-assertions:
        condition: service_completed_successfully

      # Healthchecks should be healthy.
      php-84-healthchecks:
        condition: service_healthy
      php-81-healthchecks:
        condition: service_healthy
      php-74-healthchecks:
        condition: service_healthy
      php-84-node-healthchecks:
        condition: service_healthy
      php-81-node-healthchecks:
        condition: service_healthy
      magento-php-84-healthchecks:
        condition: service_healthy
      magento-php-81-healthchecks:
        condition: service_healthy
