services:
  base-22-assertions:
    build:
      context: .
      dockerfile: Alpine.Dockerfile
      target: alpine-22-base
    command: ["bash", "/usr/local/bin/validate"]
  base-21-assertions:
    build:
      context: .
      dockerfile: Alpine.Dockerfile
      target: alpine-21-base
    command: ["bash", "/usr/local/bin/validate"]
  base-18-assertions:
    build:
      context: .
      dockerfile: Alpine.Dockerfile
      target: alpine-18-base
    command: ["bash", "/usr/local/bin/validate"]
  base-15-assertions:
    build:
      context: .
      dockerfile: Alpine.Dockerfile
      target: alpine-15-base
    command: ["bash", "/usr/local/bin/validate"]

  # Java inherit from Base
  java-21-assertions:
    build:
      context: .
      dockerfile: Java.Dockerfile
      target: java-21-base
    command: ["bash", "/usr/local/bin/validate"]
  java-17-assertions:
    build:
      context: .
      dockerfile: Java.Dockerfile
      target: java-17-base
    command: ["bash", "/usr/local/bin/validate"]
  java-11-assertions:
    build:
      context: .
      dockerfile: Java.Dockerfile
      target: java-11-base
    command: ["bash", "/usr/local/bin/validate"]
  java-8-assertions:
    build:
      context: .
      dockerfile: Java.Dockerfile
      target: java-8-base
    command: ["bash", "/usr/local/bin/validate"]

  # Java War Machine inherit from Base+Java
  java-21-war-machine-assertions:
    build:
      context: .
      dockerfile: Java.Dockerfile
      target: java-war-machine-21-base
    command: ["bash", "/usr/local/bin/validate"]
  java-17-war-machine-assertions:
    build:
      context: .
      dockerfile: Java.Dockerfile
      target: java-war-machine-17-base
    command: ["bash", "/usr/local/bin/validate"]
  java-11-war-machine-assertions:
    build:
      context: .
      dockerfile: Java.Dockerfile
      target: java-war-machine-11-base
    command: ["bash", "/usr/local/bin/validate"]

  # Java Tomcat inherit from Base+Java
  java-21-tomcat-assertions:
    build:
      context: .
      dockerfile: Java.Dockerfile
      target: java-tomcat-21-base
    command: ["bash", "/usr/local/bin/validate"]
  java-17-tomcat-assertions:
    build:
      context: .
      dockerfile: Java.Dockerfile
      target: java-tomcat-17-base
    command: ["bash", "/usr/local/bin/validate"]
  java-11-tomcat-assertions:
    build:
      context: .
      dockerfile: Java.Dockerfile
      target: java-tomcat-11-base
    command: ["bash", "/usr/local/bin/validate"]
  java-8-tomcat-assertions:
    build:
      context: .
      dockerfile: Java.Dockerfile
      target: java-tomcat-8-base
    command: ["bash", "/usr/local/bin/validate"]

  # PHP inherit from Base
  php-84-assertions:
    build:
      context: .
      dockerfile: PHP.Dockerfile
      target: php-84-base
    command: ["bash", "/usr/local/bin/validate"]
  php-81-assertions:
    build:
      context: .
      dockerfile: PHP.Dockerfile
      target: php-81-base
    command: ["bash", "/usr/local/bin/validate"]
  php-74-assertions:
    build:
      context: .
      dockerfile: PHP.Dockerfile
      target: php-74-base
    command: ["bash", "/usr/local/bin/validate"]

  # PHP+Node inherit from Base+PHP
  php-84-node-assertions:
    build:
      context: .
      dockerfile: PHP.Dockerfile
      target: php-84-node-base
    command: ["bash", "/usr/local/bin/validate"]
  php-81-node-assertions:
    build:
      context: .
      dockerfile: PHP.Dockerfile
      target: php-81-node-base
    command: ["bash", "/usr/local/bin/validate"]

  # Magento inherit from Base+PHP+Node
  magento-php-84-assertions:
    build:
      dockerfile: Magento.Dockerfile
      target: magento-84-node-base
    command: ["bash", "/usr/local/bin/validate"]
  magento-php-81-assertions:
    build:
      dockerfile: Magento.Dockerfile
      target: magento-81-node-base
    command: ["bash", "/usr/local/bin/validate"]
