#!/usr/bin/env bash
set -e
cd "$(dirname "$0")"
source $(dirname "$0")/.common.sh
DC_CMD="docker compose -f test.yml "

function cleanup {
	echo "Cleaning up containers..."
	$DC_CMD down --timeout 0 --remove-orphans --volumes >/dev/null || true
}
function finalize {
	cleanup
}
trap finalize EXIT

#if $1 is passed, thats our target
if [ -n "$1" ]; then
	$DC_CMD --progress plain up --build $1
	exit $?
fi

echo "Pulling base images ... "
docker_pull_base_images "Alpine.Dockerfile"

cleanup

echo "Running tests ... "
if ! $DC_CMD --progress none up --detach --wait --build; then
	banner "Failure!" | colorize $COLOR_RED
	echo "Container build tests failed."
	echo "  Hint: Try running ${COLOR_YELLOW}${0} failed-target${COLOR_RESET} to see more details."
	ring_bell "fail"
	exit 1
fi

echo "${COLOR_GREEN}Container build tests passed.${COLOR_RESET}"
ring_bell "okay"
exit 0
