include:
  - test-healthchecks.yml
  - test-versions-assertions.yml

services:
  test:
    build:
      dockerfile_inline: |
        FROM alpine:3.21
        RUN apk add --no-cache bash bash-completion curl
    command: ["sleep", "infinity"]
    depends_on:
      # Validation scripts should just exit 0 if the container is happy
      magento-php84-node-test:
        condition: service_completed_successfully
      magento-php81-node-test:
        condition: service_completed_successfully
      php84-node-test:
        condition: service_completed_successfully
      php81-node-test:
        condition: service_completed_successfully
      base-21:
        condition: service_completed_successfully
      base-18:
        condition: service_completed_successfully
      base-15:
        condition: service_completed_successfully

      # Healthchecks should be healthy.
      magento-php84:
        condition: service_healthy
      magento-php81:
        condition: service_healthy
      php84-node:
        condition: service_healthy
      php81-node:
        condition: service_healthy
      php84:
        condition: service_healthy
      php81:
        condition: service_healthy
      php74:
        condition: service_healthy
