include:
  - test-healthchecks.yml
  - test-versions-assertions.yml

services:
  test:
    image: alpine:3.22
    command: ["sleep", "infinity"]
    depends_on:
      # Validation scripts should just exit 0 if the container is happy
      magento-php84-assertions:
        condition: service_completed_successfully
      magento-php81-assertions:
        condition: service_completed_successfully
      php84-node-assertions:
        condition: service_completed_successfully
      php81-node-assertions:
        condition: service_completed_successfully
      base-22-assertions:
        condition: service_completed_successfully
      base-21-assertions:
        condition: service_completed_successfully
      base-18-assertions:
        condition: service_completed_successfully
      base-15-assertions:
        condition: service_completed_successfully

      # Healthchecks should be healthy.
      magento-php84-healthchecks:
        condition: service_healthy
      magento-php81-healthchecks:
        condition: service_healthy
      php84-node-healthchecks:
        condition: service_healthy
      php81-node-healthchecks:
        condition: service_healthy
      php84-healthchecks:
        condition: service_healthy
      php81-healthchecks:
        condition: service_healthy
      php74-healthchecks:
        condition: service_healthy
