#!/usr/bin/env bash
source $(dirname "$0")/../common.sh
# runit provides the exit code of the last process in the environment variable $1
LAST_PROCESS_EXIT_CODE=$1
MAGENTO_STARTUP_FAILURE_DELAY=${MAGENTO_STARTUP_FAILURE_DELAY:-60}

if [[ $LAST_PROCESS_EXIT_CODE -ne 0 ]]; then
	echo "[$DIR] Magento startup failed with exit code $LAST_PROCESS_EXIT_CODE."
	echo "[$DIR] Check the logs for more details."
	echo "[$DIR] We're gonna wait $MAGENTO_STARTUP_FAILURE_DELAY seconds before restarting."
	sleep $MAGENTO_STARTUP_FAILURE_DELAY
	exit 0
fi

echo "[$DIR] Magento startup finished successfully."
touch /etc/services.d/magento/done
sleep infinity
