#!/usr/bin/env bash
# shellcheck disable=SC2155
CURRENT_DIR=$(dirname "$(realpath "$0")")
PROCESS_NAME="magento"
source $(dirname "$0")/../common.sh
MAGENTO_MODE=${MAGENTO_MODE:-development}
TASKSD_DIR="${CURRENT_DIR}/tasks.d"
SECONDS=0
function fixCachePerms() {
	echo "[$DIR] Fixing cache ownership"
	chown -R app:app /app/var
}
function runStartupTasks() {
	if [ ! -d "$TASKSD_DIR" ]; then
		echo "[$DIR] Tasks directory ${COLOR_YELLOW}${TASKSD_DIR}${COLOR_RESET} missing, skipping."
		exit 0
	fi
	local task_count=$(find "$TASKSD_DIR" -maxdepth 1 -type f -name '*.sh' | wc -l)
	if [ "$task_count" -eq 0 ]; then
		echo "[$DIR:DevTasks] No development tasks found in ${COLOR_YELLOW}${TASKSD_DIR}${COLOR_RESET}, skipping."
		exit 0
	fi
	echo "[$DIR:DevTasks] There are ${COLOR_YELLOW}${task_count}${COLOR_RESET} development tasks to run"
	for script in "$TASKSD_DIR"/*.sh; do
		echo "[$DIR:DevTasks]  > Running ${COLOR_GREY}${script}${COLOR_RESET}"
		su -c "bash $script" app
		if [ $? -ne 0 ]; then
			echo "[$DIR:DevTasks]  > Error running ${COLOR_GREY}${script}${COLOR_RESET}"
			exit 1
		fi
	done
	# After running, we should probably fix the perms just in case.
	fixCachePerms
}

rm /etc/services.d/magento/done >/dev/null 2>&1 || true
touch /etc/services.d/magento/starting

fixCachePerms
if [ $(which magento | wc -l) -eq 0 ]; then
	rm /etc/services.d/magento/starting
	echo "[$DIR] Error: '${COLOR_YELLOW}magento${COLOR_RESET}' utility binary is not detectable!"
	echo "[$DIR]  You may need to add it to your ${COLOR_YELLOW}PATH${COLOR_RESET}."
	echo "[$DIR]   PATH: ${COLOR_GREY}${PATH}${COLOR_RESET}"
	exit 0
fi
echo "[$DIR] Starting Magento"
runStartupTasks
echo "[$DIR] Magento startup finished in ${SECONDS} seconds."

rm /etc/services.d/magento/starting
touch /etc/services.d/magento/done
