#!/usr/bin/env bash
PROCESS_COLOR=199
source /etc/services.d/common.sh
# if WAR_FILE is not set, we need to detect the only .war file in the directory.
# If there is more than one, we will exit with an error.
if [ -z "${WAR_FILE}" ]; then
	WAR_FILES=($(find . -maxdepth 1 -type f -name "*.war"))
	if [ ${#WAR_FILES[@]} -eq 0 ]; then
		echo "${COLOR_RED}No .war files found in ${PWD}.${COLOR_RESET}"
		exit 1
	elif [ ${#WAR_FILES[@]} -gt 1 ]; then
		echo "${COLOR_RED}Multiple .war files found: ${WAR_FILES[*]} ${COLOR_RESET}"
		exit 1
	else
		WAR_FILE=$(realpath "${WAR_FILES[0]}")
		echo "${COLOR_YELLOW}Detected WAR file: ${WAR_FILE}${COLOR_RESET}"
	fi
else
	echo "${COLOR_YELLOW}Using WAR file from environment variable \$WAR_FILE: ${WAR_FILE}${COLOR_RESET}"
fi

# Update our process name
PROCESS_NAME="${WAR_FILE##*/}"
unset PROCESS_COLOR
set_dir_name # Update the [DIR] variable

(
	echo "Running: ${COLOR_YELLOW}${WAR_FILE}${COLOR_RESET}"
	echo " > java ${JAVA_OPTS} -jar ${WAR_FILE}"
	su app -c "java $JAVA_OPTS -jar ${WAR_FILE}"
) 2>&1 | (while IFS= read -r; do echo "${COLOR_RESET}[${DIR}] $REPLY"; done)
