#!/usr/bin/env bash
source /usr/local/share/common.sh
(
	MAGENTO_INDEX_INTERVAL_SECONDS=86400 # Default cron interval in seconds
	# wait until /etc/services.d/magento/done exists
	if [ ! -f /etc/services.d/magento/done ]; then
		echo "Waiting for Magento to be ready ..."
		while [ ! -f /etc/services.d/magento/done ]; do
			sleep 1
		done
	fi
	echo "Magento is ready, starting indexes. Running every ${COLOR_YELLOW}${MAGENTO_INDEX_INTERVAL_SECONDS} seconds${COLOR_RESET}."

	# Run once first to populate indexes. If it fails, disable indexing.
	if ! chpst -u app magento cron:run --group index; then
		echo "Magento indexes failed to run, disabling indexes."
		sleep infinity
		exit 1
	fi

	# Start running cron
	while true; do
		(
			flock -s 200
			START_SECONDS=$SECONDS
			chpst -u app magento cron:run --group index
			echo "Magento indexes completed in ${COLOR_YELLOW}$((SECONDS - START_SECONDS)) seconds${COLOR_RESET}. Waiting ${COLOR_YELLOW}${MAGENTO_INDEX_INTERVAL_SECONDS} seconds${COLOR_RESET} before next run."
		) 200>/var/run/magento-cron.lock || {
			echo "Magento indexes failed to run, retrying in ${COLOR_YELLOW}${MAGENTO_INDEX_INTERVAL_SECONDS} seconds${COLOR_RESET}."
		}
		sleep $MAGENTO_INDEX_INTERVAL_SECONDS
	done
) 2>&1 | (while IFS= read -r; do echo "${COLOR_RESET}[${DIR}] $REPLY"; done)
