#!/usr/bin/env bash
source /usr/local/share/common.sh

echo "Running dotnet service from directory: $DOTNET_WATCH_DIR"
cd $DOTNET_WATCH_DIR
(
	echo "Starting .NET watch in ${COLOR_YELLOW}${PWD}${COLOR_RESET} ..."
	exec dotnet watch run
) 2>&1 | (while IFS= read -r; do echo "${COLOR_RESET}[${DIR}] $REPLY"; done)
