#!/usr/bin/env bash
source /usr/local/share/common.sh
(
	MAGENTO_CONSUMER_INTERVAL_SECONDS=300 # Default cron interval in seconds
	# wait until /etc/services.d/magento/done exists
	if [ ! -f /etc/services.d/magento/done ]; then
		echo "Waiting for Magento to be ready ..."
		while [ ! -f /etc/services.d/magento/done ]; do
			sleep 1
		done
	fi
	echo "Magento is ready, starting consumers."

	# Run once first to populate cron lists. If it fails, disable cron.
	if ! chpst -u app magento cron:run --group consumers; then
		echo "[$DIR] Magento consumers failed to run, disabling consumers."
		sleep infinity
		exit 1
	fi

	# Start running cron
	while true; do
		(
			flock -s 200
			START_SECONDS=$SECONDS
			chpst -u app magento cron:run --group consumers
			echo "[$DIR] Magento consumers completed in $((SECONDS - START_SECONDS)) seconds."
		) 200>/var/run/magento-cron.lock || {
			echo "[$DIR] Magento consumers failed to run, retrying in $MAGENTO_CONSUMER_INTERVAL_SECONDS seconds."
		}
		sleep $MAGENTO_CONSUMER_INTERVAL_SECONDS
	done
) 2>&1 | (while IFS= read -r; do echo "${COLOR_RESET}[${DIR}] $REPLY"; done)
