#!/usr/bin/env bash
source /usr/local/share/common.sh
(
	# wait until /etc/services.d/magento/done exists
	if [ ! -f /etc/services.d/magento/done ]; then
		echo "Waiting for Magento to be ready ..."
		while [ ! -f /etc/services.d/magento/done ]; do
			sleep 1
		done
	fi
	echo "Magento is ready, starting cron."

	# Run once first to populate cron lists. If it fails, disable cron.
	if ! chpst -u app magento cron:run; then
		echo "[$DIR] Magento cron failed to run, disabling cron."
		sleep infinity
		exit 1
	fi

	# Start running cron
	while true; do
		(
			flock -s 200
			chpst -u app magento cron:run
		) 200>/var/run/magento-cron.lock || {
			echo "[$DIR] Magento cron failed to run, retrying in 60 seconds."
		}
		sleep 60
	done
) 2>&1 | (while IFS= read -r; do echo "${COLOR_RESET}[${DIR}] $REPLY"; done)
