#!/usr/bin/env bash
source /usr/local/share/common.sh
(
	MAGENTO_CRON_INTERVAL_SECONDS=300 # Default cron interval in seconds
	# wait until /etc/services.d/magento/done exists
	if [ ! -f /etc/services.d/magento/done ]; then
		echo "Waiting for Magento to be ready ..."
		while [ ! -f /etc/services.d/magento/done ]; do
			sleep 1
		done
	fi
	echo "Magento is ready, starting cron. Running every ${COLOR_YELLOW}${MAGENTO_CRON_INTERVAL_SECONDS}${COLOR_RESET} seconds."

	# Run once first to populate cron lists. If it fails, disable cron.
	if ! chpst -u app magento cron:run --group "${MAGENTO_CRON_GROUP:-"default"}"; then
		echo "[$DIR] Magento cron failed to run, disabling cron."
		sleep infinity
		exit 1
	fi

	# Start running cron
	while true; do
		(
			flock -s 200
			START_SECONDS=$SECONDS
			chpst -u app magento cron:run --group "${MAGENTO_CRON_GROUP:-"default"}"
			echo "Magento cron completed in $((SECONDS - START_SECONDS)) seconds. Waiting ${MAGENTO_CRON_INTERVAL_SECONDS} seconds before next run."
		) 200>/var/run/magento-cron.lock || {
			echo "Magento cron failed to run, retrying in ${MAGENTO_CRON_INTERVAL_SECONDS} seconds."
		}
		sleep $MAGENTO_CRON_INTERVAL_SECONDS
	done
) 2>&1 | (while IFS= read -r; do echo "${COLOR_RESET}[${DIR}] $REPLY"; done)
