#!/usr/bin/env bash
source $(dirname "$0")/../common.sh
(
	echo "Starting Cron Service in ${COLOR_YELLOW}${PWD}${COLOR_RESET} ..."
	exec crond -n -P -s
) 2>&1 | (while IFS= read -r; do echo "${COLOR_RESET}[${DIR}] $REPLY"; done)
