name: Build

permissions:
  contents: read
  packages: write

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build PrintShop
    runs-on: ubuntu-latest
    permissions:
      checks: write # For trunk to post annotations
      contents: read # For repo checkout
    strategy:
      matrix:
        component:
          - web
          - tasks
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - uses: benzine-framework/action-setup-php@main
      - uses: benzine-framework/action-setup-docker@main
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor || secrets.GHCR_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN || secrets.GHCR_TOKEN }}
      - uses: docker/build-push-action@v6
        name: Build & Push
        with:
          context: .
          platforms: |
            linux/amd64
          push: true
          target: printshop-${{ matrix.component }}
          tags: |
            ghcr.io/matthewbaggett/printshop/${{ matrix.component }}:latest
