name: Build

permissions:
  contents: read
  packages: write

env:
  TERM: xterm-256color

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      checks: write # For trunk to post annotations
      contents: read # For repo checkout
      packages: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor || secrets.GITHUB_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v3
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3
      - name: "Run Tests"
        run: ./test
      - name: "Docker Buildx Bake (and push!)"
        uses: docker/bake-action@v6
        with:
          push: true
          source: .
          files: |
            docker-bake.hcl
